language: python

python:
  - 3.6
  - 3.7

cache:
  directories:
    - /home/travis/miniconda/

jobs:
  include:
    - stage: build
      script: ./ci/build.sh

    - stage: test
      name: derivs
      script:
        - export PATH=/home/travis/miniconda/bin:$PATH
        - python --version
        - python test_script.py tests/em/tdem

    - stage: deploy
      script: ./ci/deploy_pypi.sh
