language: python

python:
  - 3.6

 cache:
    directories:
      - /home/travis/miniconda/
      - /home/travis/anaconda/

env:
  - TEST_DIR=tests/em/fdem/inverse/derivs
  - TEST_DIR=tests/em/tdem
  - TEST_DIR="tests/em/static tests/seis tests/base tests/utils"
  - TEST_DIR=tests/flow
  - TEST_DIR="tests/em/nsem/forward tests/em/nsem/inversion"
  - TEST_DIR=tests/em/fdem/inverse/adjoint
  - TEST_DIR=tests/em/fdem/forward
  - TEST_DIR=tests/em/vrm
  - TEST_DIR=tests/pf
  - TEST_DIR=tests/docs;

jobs:
  include:
    - stage: build
      script: ./ci/build.sh

    - stage: test
      name: $TEST_DIR
      script:
        - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
        - python test_script.py $TEST_DIR

    - stage: deploy
      script: ./ci/deploy_pypi.sh
