language: python

python:
  - 3.6

 cache:
    directories:
      - /home/travis/miniconda/
      - /home/travis/anaconda/
jobs:
  include:
    - stage: build
      script: ./ci/build.sh
    - stage: test
      name: derivs
      script: python --version
    - stage: deploy
      script: ./ci/deploy_pypi.sh
