language: python

cache:
  directories:
    - /home/travis/miniconda/

stages:
  - build
  - test
  - deploy

jobs:
  include:
    - stage: build
      script: ./ci/build.sh
      python:
        - 3.6
        - 3.7

    - stage: test
      name: derivs
      script:
        - export PATH=/home/travis/miniconda/bin:$PATH
        - python --version
        - python test_script.py tests/em/tdem
      python:
        - 3.6
        - 3.7

    - stage: deploy
      script: ./ci/deploy_pypi.sh
      python: 3.6
